### ISSUE TITLE
Prebuilt binaries don't work on my device with HW v2.81

### ISSUE THREAD

**Issue by ScruffR** [gabonator/DS203#32]
I have tried all four binaries and even a locally built "GABOUI_1.hex" but none of them worked on my device.
I'm using Win7 Pro 32bit (Win8.1 Pro 32/64bit don't work) and always got a `.RDY` response, but when rebooting the device I always got a "FPGA Configuration Err" and had to reflash the whole lot FPGA_281, SYS_B160 and PA1_V110 to get my device running again after each attempt.

I guess it's due to the new FPGA chip used for HW v2.8ff

**Comment by hlinden** [comment]
Same here. Pity.

**Comment by tuxadmi** [comment]
Same problem....

**Comment by CC1337** [comment]
Same here, GABOUI_4.hex worked but killed the original firmware, too. Would be nice if this can be fixed because GABOUI_4.hex had awesome features!

**Comment by reModding** [comment]
Same here :-(

**Comment by reModding** [comment]
@CC1337 Which FPGA, SYS, ... versions do you use with GABOUI_4.hex?

**Comment by CC1337** [comment]
@reModding 
Hardware Ver 2.81
SYS Ver 1.64
APP (Plus A1) Ver 1.13

**Comment by reModding** [comment]
Hm, I copy SYS_B164, the latest GABOUI_4.hex and the FPGA_281.ADR/.BIN, but this does not work anyway with Hardware 2.81.

**Comment by gigios** [comment]
I have tried also on my 'new' dso203, HW 2.81 SYS 1.64 and APP 1.13
Also on my case I have seen many problems as "FPGA Configration Err!" message at boot phase.
The second effect is that now, when I reconnect the dso to the PC (in DFU mode), the filesystem shown 3 folders with chines chars and it is not possible to rename/delete them.
I have tried to restore the original firmware/fpga/app and all seems working fine but in DFU mode I have always the 'strange' folder structure.

Have you any idea on how restore the original filesystem? (I'm not able to change on windows 7, probably for some filename limitation that inhibit the access to the wrong files/folders).

**Comment by pit001** [comment]
Hello, I also tried to get it running. 
Have also the new HW 2.81. one time I got the Firmware running, but I didn't get a input signal.

I also have the scampled directory names (like reported from gigios)

I hope there is a chance to fix it. 
Thx, Pit

Hardware Ver 2.81
SYS Ver 1.64
APP (Plus A1) Ver 1.13

**Comment by gigios** [comment]
I'm not sure but seems that the project is died!
There is not any answer to any question for months.

What I have seen on the seeedstudio forum is that, probably, the incompatibility is raised from the memory management. Seems that the trick used in the app, in the HW 2.81 overwrite part of the memory used by the FPGA.

**Comment by Serveurperso** [comment]
Please same problem here HW 2.81 fail

**Comment by 6HJS** [comment]
I am working on HW2.81 and hops to make the GABOUI works.

by modifying the \DS203-master\Source\HwLayer\ArmM3\lds\app1_win.lds

line 5 	
ROM (rx) : ORIGIN = 0x0804C000, LENGTH = 200K
to 
ROM (rx) : ORIGIN = 0x0802C000, LENGTH = 200K
to aviod overwritting FPGA field, I can got DS203 starts up.

Wildcat talked about the memory mapping issue here.
http://www.seeedstudio.com/forum/viewtopic.php?f=26&t=5512#p20206

but it gives a SDK Warning: Invalid request
and
699 ../Source/Framework/Eval.h Assertion fail.
![20160324_170534](https://cloud.githubusercontent.com/assets/13013462/14010338/2647c320-f1e4-11e5-8333-6e0ce410ee11.jpg)

**Comment by 6HJS** [comment]
Well here is my sollution, it is sample and works well.
Download the whole Github repository in zip file.
Unzip to a path contains NO blank space.
Download the ARM toolchain form [https://sourcery.mentor.com/sgpp/lite/arm/portal/package8735/public/arm-none-eabi/arm-2011.03-42-arm-none-eabi-i686-mingw32.tar.bz2](url)
And past the \arm-2011.03 to \DS203-master\Toolchain\
Edit the \DS203-master\Source\HwLayer\ArmM3\lds\app1_win.lds
line 5
ROM (rx) : ORIGIN = 0x0804C000, LENGTH = 200K
to
ROM (rx) : ORIGIN = 0x0802C800, LENGTH = 200K
Run the make.bat in \DS203-master\Build\arm_win32
Finally copy the GABOUI_1.hex form \DS203-master\Bin to your DFU driver.
Reboot the device with out pushing any key.
![20160324_183649](https://cloud.githubusercontent.com/assets/13013462/14011692/804cb252-f1f0-11e5-9f6a-792d683db3e6.jpg)
It runs well without warning jumps out any more.

**Comment by pit001** [comment]
Hi 6HJS, good job ! I wait sooo long for an update :)
Can you correct your links an maybe upload the hex files ? Thx Peter

**Comment by pit001** [comment]
Hello, tryed it and it's working !!!

Some hints: 
- The Link content to the ARM toolchain is wrong  - copy the text to your Browser
- If you use the ARM toolchain you have to change the makefile.bat (set CBASE=..\Toolchain\arm-2011.03\bin\)
- it's makefile.bat not make.bat
- in my ARM toolchain some files has zero-size. So I use the http://pub.valky.eu/arm-2011.03-lite.zip 
 (It's smaler, only one time packed and it works).

Attached - the resulting .hex file (delete the ending .txt)
[GABOUI_1.hex.txt](https://github.com/gabonator/DS203/files/187541/GABOUI_1.hex.txt)

**Comment by gabonator** [comment]
6HJS, great work! Which HW versions require the linker script change? I will update the linker script and generate firmware images for both older hw and newer hw

**Comment by 6HJS** [comment]
@gabonator Only the hardware version with ICE40 FPGA needs to change the linker script.

The structure of FPGA image is also changed, therefore the LOGO and FPGA version in your system can not display properly.

The Chinese developer has released the FPGA source code, please have a look.

http://minidso.com/forum.php?mod=viewthread&tid=149&extra=page%3D1

**Comment by joeig** [comment]
Works!! Thank you!

**Comment by CC1337** [comment]
GAB_N2.hex works on my HW 2.81 as well! Thanks!
