### ISSUE TITLE
x10 Probe

### ISSUE THREAD

**Issue by QuentinC** [gabonator/DS203#8]
Hi,

First, thanks a lot for your work, it's great and very usefull, I'm gonna use it everytime !
But something else I've seen: setting the probe to x10 dont change anything on the screen display, shouldn't it show somethine 10 times higher than in x1 ?

Thanks !

Quentin

**Comment by FR4NK5T3R** [comment]
Is it in the new code yet please?

**Comment by QuentinC** [comment]
Not yet, I've made a pull request from my fork: https://github.com/QuentinC/DS203
You can clone mine to have the probe (working well), but it isn't in the main repository yet !

**Comment by FR4NK5T3R** [comment]
Hi QuentinC I would really like to get X10 working on my DS203.
Can you tell me how please

**Comment by QuentinC** [comment]
The updated binaries are in my rpo: https://github.com/QuentinC/DS203 !
I've sent a pull request !
